### ISSUE TITLE
Treinamento do curso

### ISSUE THREAD

**Issue by Elieel5** [kadu5/estudos#1]
Kadu, você ainda está no inicio do curso, porém, vamos lá para o seu primeiro teste.

Me explique para que serve o favicon? e qual a sua necessidade em um site?

**Comment by kadu5** [comment]
para oque serve o favicon:
ele serve para fazer a identifcação do site, ele também faz que o seu site seja identificado
de uma forma mais fácil e mais rapida
ex:quando você está com muitas abas abertas você pode identificar qual era o  site que você
estava usando anteriormente
