### ISSUE TITLE
Teste 01

### ISSUE THREAD

**Issue by Elieel5** [kadu5/estudos#2]
Qual é a estrutura correta de um HTML ?
Qual são as tag de títulos disponíveis em HTML ?
Qual é o significado de HTML ?
HTML pode ser considerado uma ligação de programação, sim ou não ? Descreva o motivo da opção do SIM e do NÃO...
Qual é a finalidade do <!DOCTYPE html> no inicio do arquivo HTML  ?

**Comment by kadu5** [comment]
A estrutura do HTML é (<DOCTAYPE html>, <html>,<head> <body>
As tags de títulos são ( <title> <h1> <h2> <h3> <h4> <h5> <h6>
o significado de html é= hypertext markup languege.
O HTML não pode ser considerado uma linguagem de programação, porque é uma linguagem de desenvolvimento.
A fidelidade do inico do html, ele permite a construção do site é que possa adicionar vidéos e imagens no site.

**Comment by kadu5** [comment]
vou colocar a estrutura aqui porque ali no foi (DOCTYAPE, HTML, HEAD, BODY)
Os títulos são(title,h1,h2.h3,h4,h5,h6)
